#!/bin/bash
# Graduate Career Platform - Setup Checklist
# This is a quick reference for setting up all new features

echo "=================================="
echo "Graduate Career Platform Setup"
echo "=================================="
echo ""

# Step 1: Migrations
echo "✓ STEP 1: Running Database Migrations..."
echo "  Command: php artisan migrate"
echo "  Creates: notifications, activity_logs, files tables"
echo ""

# Step 2: Storage Link
echo "✓ STEP 2: Creating Storage Link..."
echo "  Command: php artisan storage:link"
echo "  Creates symbolic link for public file access"
echo ""

# Step 3: Verify Installation
echo "✓ STEP 3: Verify Installation"
echo "  Check these files were added:"
echo "  - app/Models/Notification.php"
echo "  - app/Models/ActivityLog.php"
echo "  - app/Models/File.php"
echo "  - app/Http/Controllers/NotificationController.php"
echo "  - app/Http/Controllers/SearchController.php"
echo "  - app/Http/Controllers/FileController.php"
echo "  - app/Services/NotificationService.php"
echo "  - app/Policies/NotificationPolicy.php"
echo "  - resources/views/notifications/index.blade.php"
echo ""

# Step 4: New Routes
echo "✓ STEP 4: New Routes Available"
echo "  Notifications:"
echo "    GET    /notifications"
echo "    GET    /notifications/unread-count"
echo "    GET    /notifications/recent"
echo "    PATCH  /notifications/{id}/read"
echo "    DELETE /notifications/{id}"
echo ""
echo "  Search:"
echo "    GET    /search?q=query&type=jobs"
echo "    GET    /search/advanced"
echo ""
echo "  Files:"
echo "    POST   /files/upload"
echo "    GET    /files"
echo "    DELETE /files/{id}"
echo "    GET    /files/{id}/download"
echo ""

# Step 5: Quick Test
echo "✓ STEP 5: Test Features"
echo ""
echo "  1. Notifications:"
echo "     - Go to /notifications"
echo "     - Apply for a job to trigger notification"
echo ""
echo "  2. Search:"
echo "     - Use /search?q=keyword"
echo "     - Try searching for a job title"
echo ""
echo "  3. Files:"
echo "     - POST /files/upload with resume"
echo "     - Visit /files to see uploaded files"
echo ""

# Step 6: Documentation
echo "✓ STEP 6: Read Documentation"
echo ""
echo "  - NEW_FEATURES.md - Complete feature reference"
echo "  - IMPLEMENTATION_GUIDE.md - Setup and usage guide"
echo ""

# Summary
echo "=================================="
echo "SETUP SUMMARY"
echo "=================================="
echo ""
echo "What was added:"
echo "  1. ✅ Notification System"
echo "  2. ✅ Activity Logging"
echo "  3. ✅ Global Search"
echo "  4. ✅ File Management"
echo "  5. ✅ Advanced Authorization"
echo ""
echo "Next steps:"
echo "  1. Run: php artisan migrate"
echo "  2. Run: php artisan storage:link"
echo "  3. Test the features"
echo "  4. Review documentation files"
echo ""
echo "Database Tables Created:"
echo "  - notifications"
echo "  - activity_logs"
echo "  - files"
echo ""
echo "=================================="
echo "Setup Complete! Start testing! 🚀"
echo "=================================="
